// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiMysqlSdk9.Data;

#nullable disable

namespace RestApiMysqlSdk9.Migrations
{
    [DbContext(typeof(AppDbContext1))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RestApiMysqlSdk9.Models.Agence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("adresse")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Adresse"), "utf8mb4");

                    b.Property<string>("Aimposition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Aimposition"), "utf8mb4");

                    b.Property<string>("Banque")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("banque")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Banque"), "utf8mb4");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Email"), "utf8mb4");

                    b.Property<string>("Fimposition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Fimposition"), "utf8mb4");

                    b.Property<string>("Horaire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("horaire")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Horaire"), "utf8mb4");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("logo")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Logo"), "utf8mb4");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Nom"), "utf8mb4");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("presentation")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Presentation"), "utf8mb4");

                    b.Property<string>("Proprietaire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("proprietaire")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Proprietaire"), "utf8mb4");

                    b.Property<string>("Rcommerce")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Rcommerce"), "utf8mb4");

                    b.Property<string>("Rib")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rib")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Rib"), "utf8mb4");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("telephone")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Telephone"), "utf8mb4");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("agence", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("adresse");

                    b.Property<string>("DateNaiss")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date_naiss");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Narticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("narticle");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nature");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nif");

                    b.Property<string>("Nis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nis");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom");

                    b.Property<string>("Passe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("passe");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("raison");

                    b.Property<string>("Rcommerce")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rcommerce");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_client", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cond")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cond")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Cond"), "utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_condition", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntContrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Clientid")
                        .HasColumnType("int(11)")
                        .HasColumnName("clientid");

                    b.Property<string>("Datedebut")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("datedebut");

                    b.Property<string>("Datefin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("datefin");

                    b.Property<string>("Montant")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("montant");

                    b.Property<string>("Numerocontrat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numerocontrat");

                    b.Property<string>("Typecontrat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("typecontrat");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_contrat", (string)null);
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("etat");

                    b.Property<int>("IdClient")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_client");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("num");

                    b.Property<string>("Reste")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reste");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total");

                    b.Property<string>("Versement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("versement");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_facture", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntLigneProforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("designation");

                    b.Property<int>("IdProforma")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proforma");

                    b.Property<string>("Pu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pu");

                    b.Property<string>("Qtt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("qtt");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("unite");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_ligne_proforma", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntLigneTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("designation");

                    b.Property<int>("IdTravail")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_travail");

                    b.Property<string>("Pu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pu");

                    b.Property<string>("Qtt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("qtt");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("unite");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_ligne_travail", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cautionnement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cautionnement");

                    b.Property<int>("Client")
                        .HasColumnType("int(11)")
                        .HasColumnName("client");

                    b.Property<int>("Conducteur")
                        .HasColumnType("int(11)")
                        .HasColumnName("conducteur");

                    b.Property<string>("DateDeb")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date_deb");

                    b.Property<string>("DateFin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date_fin");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("etat");

                    b.Property<string>("KmDepart")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("km_depart");

                    b.Property<string>("KmJour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("km_jour");

                    b.Property<string>("KmRetour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("km_retour");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mode_paiement");

                    b.Property<string>("Montant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("montant");

                    b.Property<string>("MontantReste")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("montant_reste");

                    b.Property<string>("MontantVerse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("montant_verse");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("num");

                    b.Property<string>("Prixu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("prixu");

                    b.Property<int>("Vehicule")
                        .HasColumnType("int(11)")
                        .HasColumnName("vehicule");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_location", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntMarque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(9)")
                        .HasColumnName("id_marque");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marque");

                    b.HasKey("IdMarque")
                        .HasName("PRIMARY");

                    b.ToTable("ent_marque", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntModele", b =>
                {
                    b.Property<int>("IdModele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_modele");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdModele"));

                    b.Property<int>("IdMarque")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_marque");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modele");

                    b.HasKey("IdModele")
                        .HasName("PRIMARY");

                    b.ToTable("ent_modele", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntProforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("etat");

                    b.Property<int>("IdClient")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_client");

                    b.Property<int>("IdTravail")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_travail");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("num");

                    b.Property<string>("Reste")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reste");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total");

                    b.Property<string>("Validite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("validite");

                    b.Property<string>("Versement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("versement");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_proforma", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateDepart")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date_depart");

                    b.Property<string>("DateRetour")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date_retour");

                    b.Property<int>("IdClient")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_client");

                    b.Property<int>("IdVehicule")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_vehicule");

                    b.Property<string>("NbJour")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("nb_jour");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_client");

                    b.Property<string>("NomVehicule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_vehicule");

                    b.Property<string>("Somme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("somme");

                    b.Property<string>("TypePaiement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_paiement");

                    b.Property<string>("Valider")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("valider");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_reservation", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("etat");

                    b.Property<int>("IdClient")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_client");

                    b.Property<int>("IdFacture")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_facture");

                    b.Property<int>("IdProforma")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proforma");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("num");

                    b.Property<string>("Reste")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reste");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("total");

                    b.Property<string>("Versement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("versement");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_travail", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntUser", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("user");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("etat");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("password");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("profile");

                    b.HasKey("User")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "User" }, "user")
                        .IsUnique();

                    b.ToTable("ent_user", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntUser2", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Passe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("User")
                        .HasName("PRIMARY");

                    b.ToTable("ent_user2", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntVehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Abs")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ABS");

                    b.Property<string>("AgenceAssurance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("AGENCE_ASSURANCE");

                    b.Property<string>("AgenceControl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("AGENCE_CONTROL");

                    b.Property<bool?>("AirbagConducteur")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("AirbagPassager")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Alarme")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AntiVol")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apercu")
                        .HasColumnType("longtext")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Apercu"), "utf8mb4");

                    b.Property<bool>("BoitePharmacie")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BoiteSendrie")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CableRemorquage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CameraRecul")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CapteurCollision")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Climatiseur")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("CricManivelle")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DateVidange")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DATE_VIDANGE");

                    b.Property<string>("DebAssurance")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DEB_ASSURANCE");

                    b.Property<string>("DebControl")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DEB_CONTROL");

                    b.Property<bool?>("DirectionAssiste")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EcranTactile")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Energie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Energie"), "utf8mb4");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("FeuAntiBrouillard")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FinAssurance")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FIN_ASSURANCE");

                    b.Property<string>("FinControl")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FIN_CONTROL");

                    b.Property<bool>("JantesAlliages")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("int(11)");

                    b.Property<int>("KmRetourVidange")
                        .HasColumnType("int(11)")
                        .HasColumnName("KM_RETOUR_VIDANGE");

                    b.Property<int>("KmVidange")
                        .HasColumnType("int(11)")
                        .HasColumnName("KM_VIDANGE");

                    b.Property<bool?>("LecteurCd")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Marque")
                        .HasColumnType("int(11)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModelAnnee")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Modele")
                        .HasColumnType("int(11)");

                    b.Property<string>("NombrePlace")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("PrixParJour")
                        .HasColumnType("int(11)");

                    b.Property<bool>("RoueSecours")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SiegeAuto")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SiegesEnCuir")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("TriangeSignalisation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("VerouillageCentralise")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Vimage1")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Vimage1"), "utf8mb4");

                    b.Property<string>("Vimage2")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Vimage2"), "utf8mb4");

                    b.Property<string>("Vimage3")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Vimage3"), "utf8mb4");

                    b.Property<string>("Vimage4")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Vimage4"), "utf8mb4");

                    b.Property<string>("Vimage5")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Vimage5"), "utf8mb4");

                    b.Property<bool?>("VitresElectriques")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_vehicule", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntVehicule2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_vehicule2", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.EntVehiculeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdVehicule")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_vehicule");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("image");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ent_vehicule_image", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("RestApiMysqlSdk9.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("products", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
